export const FilterOperators = {
  EqualTo: '=',
  Between: 'between',
  LessThan: '<',
  LessThanOrEqualTo: '<=',
  GreaterThan: '>',
  GreaterThanOrEqualTo: '>=',
  In: 'in',
  NotIn: 'notIn',
  Any: 'any',
  NotNull: 'notNull',
  IsNull: 'isNull',
  NotEqualTo: '!=',
  Like: 'like',
};
